/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Circle: THREE.Mesh
    Circle001: THREE.Mesh
    Star: THREE.Mesh
    Plane008: THREE.Mesh
    Plane002: THREE.Mesh
  }
  materials: {
    ['potted cactus pot']: THREE.MeshStandardMaterial
  }
}

export function Cactus(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3dModels/Cactus.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Circle"
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials['potted cactus pot']}
      />
      <mesh
        name="Circle001"
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials['potted cactus pot']}
        position={[0, 5.647, 0]}
      />
      <mesh
        name="Star"
        castShadow
        receiveShadow
        geometry={nodes.Star.geometry}
        material={materials['potted cactus pot']}
        position={[0, 5.647, 0]}
      />
      <mesh
        name="Plane008"
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials['potted cactus pot']}
        position={[-7.134, 12.606, -9.299]}
        rotation={[-2.016, 0.096, 0.636]}
      />
      <mesh
        name="Plane002"
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials['potted cactus pot']}
        position={[6.245, 21.422, -7.658]}
        rotation={[-0.45, 0.95, -0.539]}
      />
    </group>
  )
}

useGLTF.preload('/3dModels/Cactus.glb')
