/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { Ref, forwardRef, useRef } from "react";
import { useGLTF, useAnimations, Html } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube006_1: THREE.Mesh;
    Cube006_2: THREE.Mesh;
    Cube006_3: THREE.Mesh;
    Cube007: THREE.Mesh;
    Sphere002: THREE.Mesh;
    Sphere003: THREE.Mesh;
  };
  materials: {
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["orange light"]: THREE.MeshPhysicalMaterial;
    orange: THREE.MeshStandardMaterial;
  };
};

type ActionName = "Cube.006" | "Cube.007" | "Sphere.002" | "Sphere.003";


export const GameBoy = forwardRef<THREE.Group, JSX.IntrinsicElements["group"]>((props, ref) => {

  const { nodes, materials, animations } = useGLTF(
    "/3dModels/gameBoy.glb"
  ) as GLTFResult;

  return (
    <group  {...props} dispose={null} ref={ref}>
      <group name="Scene">
      <Html  
        transform 
        style={{backfaceVisibility:'hidden',transformStyle: "preserve-3d" ,willChange: "transform"}}
        scale={0.4}
        center
        position={[0, 0.85, 0.9]}
        distanceFactor={1}
        zIndexRange={[1000,1500]}

         as="div"
        // occlude
        // rotation={[0,Math.PI/2,0]}

        >
          {props.children}
        </Html> 
        <group name="Cube006" position={[0, 0, 0]}>
          <mesh
            name="Cube006_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube006_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="Cube006_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube006_2.geometry}
            material={materials["orange light"]}
          />
          <mesh
            name="Cube006_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube006_3.geometry}
            material={materials["orange light"]}
          />
          <mesh
            name="Cube007"
            castShadow
            receiveShadow
            geometry={nodes.Cube007.geometry}
            material={materials.orange}
            position={[-0.547, -0.276, 0.434]}
            scale={0.124}
          />
          <mesh
            name="Sphere002"
            castShadow
            receiveShadow
            geometry={nodes.Sphere002.geometry}
            material={materials.orange}
            position={[0.667, -0.211, 0.966]}
            rotation={[1.573, 0.095, -0.002]}
            scale={0.162}
          />
          <mesh
            name="Sphere003"
            castShadow
            receiveShadow
            geometry={nodes.Sphere003.geometry}
            material={materials.orange}
            position={[0.361, -0.539, 0.981]}
            rotation={[1.573, 0.095, -0.002]}
            scale={0.162}
          />
        </group>
      </group>
    </group>
  );
})

useGLTF.preload("/3dModels/gameBoy.glb");
