/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useMemo, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh;
  };
  materials: {
    ["post-it"]: THREE.MeshStandardMaterial;
  };
};

export function PostIt(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/3dModels/Post-it.glb") as GLTFResult;
  const canvas = useMemo(() => {
    const canvasTemp = document.createElement("canvas");
    const size = 200
    canvasTemp.width = size
    canvasTemp.height = size * 1.41
    const ctx = canvasTemp.getContext('2d')
    if(ctx) {
      ctx.font = '30px Roboto'
      ctx.fillStyle = "White";
      ctx.fillRect(0, 0, canvasTemp.width, canvasTemp.height);
      ctx.textAlign = 'center'
      ctx.fillStyle = 'Black'
      ctx.rotate(-Math.PI/2)
      ctx.fillText("Acheter du pain", -size+40 , size/2  )
    }
    return canvasTemp
  }, [])
  const canvasTexture = useMemo(() => {
    const texture = new THREE.CanvasTexture(canvas)
    texture.flipY=false
    // texture.rotation=-Math.PI/16
    return texture
  }, [canvas])
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Plane"
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        rotation={[0,-Math.PI / 2 , -Math.PI / 2]}
      >

        <meshStandardMaterial color={'#E7AB4C'} map={canvasTexture}/>
      </mesh>
    </group>
  );
}

useGLTF.preload("/3dModels/Post-it.glb");
